#
# Find FINUFFT includes and library
#
# FINUFFT_INCLUDE_DIR - where to find finufft.h
# FINUFFT_LIBRARY     - libfinufft.so path
# FINUFFT_FOUND       - do not attempt to use if "no" or undefined.

FIND_PATH(FINUFFT_INCLUDE_DIR finufft.h
    HINTS $ENV{FINUFFT_INCLUDE_PATH} $ENV{FINUFFT_INCLUDE_DIR} $ENV{FINUFFT_PREFIX}/include $ENV{FINUFFT_DIR}/include ${PROJECT_SOURCE_DIR}/include
    PATHS ENV CPP_INCLUDE_PATH
)
#Static library has some issues and gives a cuda error at the end of compilation
FIND_LIBRARY(FINUFFT_LIBRARY_DIR libfinufft.so
    HINTS $ENV{FINUFFT_LIBRARY_PATH} $ENV{FINUFFT_LIBRARY_DIR} $ENV{FINUFFT_PREFIX}/lib64 $ENV{FINUFFT_DIR}/lib64 $ENV{FINUFFT}/lib64 ${PROJECT_SOURCE_DIR}/lib64
    PATHS ENV LIBRARY_PATH
)

IF(FINUFFT_INCLUDE_DIR AND FINUFFT_LIBRARY_DIR)
    SET( FINUFFT_FOUND "YES" )
    SET( FINUFFT_DIR $ENV{FINUFFT_DIR} )
ENDIF()

IF (FINUFFT_FOUND)
   IF (NOT FINUFFT_FIND_QUIETLY)
       MESSAGE(STATUS "Found finufft library dir: ${FINUFFT_LIBRARY_DIR}")
       MESSAGE(STATUS "Found finufft include dir: ${FINUFFT_INCLUDE_DIR}")
   ENDIF (NOT FINUFFT_FIND_QUIETLY)
ELSE (FINUFFT_FOUND)
    IF (FINUFFT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find FINUFFT!")
  ENDIF (FINUFFT_FIND_REQUIRED)
ENDIF (FINUFFT_FOUND)
