#
# Find CUFINUFFT includes and library
#
# CUFINUFFT_INCLUDE_DIR - where to find cufinufft.h
# CUFINUFFT_LIBRARY     - libcufinufft.a path
# CUFINUFFT_FOUND       - do not attempt to use if "no" or undefined.

FIND_PATH(CUFINUFFT_INCLUDE_DIR cufinufft.h
    HINTS $ENV{CUFINUFFT_INCLUDE_PATH} $ENV{CUFINUFFT_INCLUDE_DIR} $ENV{CUFINUFFT_PREFIX}/include $ENV{CUFINUFFT_DIR}/include ${PROJECT_SOURCE_DIR}/include
    PATHS ENV C_INCLUDE_PATH
)

FIND_LIBRARY(CUFINUFFT_LIBRARY_DIR libcufinufft.a
    HINTS $ENV{CUFINUFFT_LIBRARY_PATH} $ENV{CUFINUFFT_LIBRARY_DIR} $ENV{CUFINUFFT_PREFIX}/lib-static $ENV{CUFINUFFT_DIR}/lib-static $ENV{CUFINUFFT}/lib-static ${PROJECT_SOURCE_DIR}/lib-static
    PATHS ENV LIBRARY_PATH
)

IF(CUFINUFFT_INCLUDE_DIR AND CUFINUFFT_LIBRARY_DIR)
    SET( CUFINUFFT_FOUND "YES" )
ENDIF()

IF (CUFINUFFT_FOUND)
   IF (NOT CUFINUFFT_FIND_QUIETLY)
       MESSAGE(STATUS "Found cufinufft library dir: ${CUFINUFFT_LIBRARY_DIR}")
       MESSAGE(STATUS "Found cufinufft include dir: ${CUFINUFFT_INCLUDE_DIR}")
   ENDIF (NOT CUFINUFFT_FIND_QUIETLY)
ELSE (CUFINUFFT_FOUND)
    IF (CUFINUFFT_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find CUFINUFFT!")
  ENDIF (CUFINUFFT_FIND_REQUIRED)
ENDIF (CUFINUFFT_FOUND)
