/**
 * @file CosmologyICRandom.h
 * @brief Stateless Gaussian Fourier coefficients with a versioned physical-mode key.
 * @ingroup cosmology_core
 * @see cosmology_numerics cosmology_contracts cosmology_validation
 *
 * @par Purpose and position in the initializer
 * This header implements the random part of `ic_rng=mode_hash_v1`. Its public
 * entry point, cosmology::modeGaussian(), maps a realization seed and a signed
 * integer mode @f$\boldsymbol m=(m_x,m_y,m_z)@f$ to a dimensionless complex draw
 * @f$G_{\boldsymbol m}@f$. The arguments named kx, ky and kz are these integers,
 * not the dimensional wave vector @f$\boldsymbol k=2\pi\boldsymbol m/L@f$ and
 * not wrapped FFT array indices. The pipeline is
 * @f[
 * (s,\boldsymbol m)\longrightarrow(s,\boldsymbol m_c,\mathrm{conjugate})
 * \longrightarrow\mathrm{bytes}\longrightarrow\mathrm{SHA256}
 * \longrightarrow(u_1,u_2)\longrightarrow G_{\boldsymbol m}.
 * @f]
 * Simulation::initializeModes() selects retained modes, multiplies by
 * @f$\sqrt{P_0(k)/L^3}@f$, and applies the cell-centre sampling phase. Growth,
 * the inverse FFT and 1LPT particle displacements are separate operations.
 * The existing `legacy` RNG path does not call this implementation.
 *
 * @par Why use physical modes as keys?
 * A sequential RNG associates draws with traversal order; an index-keyed RNG
 * can associate them with the mesh size. Here the seed and Cartesian mode alone
 * determine the draw. The same mode can therefore be regenerated by any MPI
 * rank or CPU/GPU thread without advancing a stream, skipping draws or storing
 * an RNG pool. Adding finer-grid modes or changing a cutoff leaves draws for
 * retained modes unchanged. For equal box, spectrum and seed, a common positive
 * cutoff below both meshes' Nyquist supplies the same underlying field sampled
 * on different lattices. With cutoff=0, finer meshes retain additional modes.
 * Equal integer modes in different boxes have different physical wave numbers;
 * equal random draws alone do not imply equal physical density coefficients.
 *
 * @par Hermitian pairing
 * The canonical member @f$\boldsymbol m_c@f$ of a nonzero pair
 * @f$\{\boldsymbol m,-\boldsymbol m\}@f$ has its first nonzero component,
 * in x/y/z order, positive. Both requests hash that same canonical member;
 * the negative member negates only the final imaginary component. Thus
 * @f$G_{-\boldsymbol m}=G_{\boldsymbol m}^{*}@f$ within one arithmetic backend,
 * which is the conjugate symmetry required for a real Fourier field.
 * Example: (2,-1,0) and (-2,1,0) share one digest, whereas (1,-2,0) has another
 * key. Simulation::initializeModes() excludes DC and all Nyquist planes before
 * calling this routine; this header has no mesh dimension with which to identify
 * self-conjugate discrete Nyquist modes.
 *
 * @par Versioned compatibility contract
 * The exact domain string including NUL, integer widths and byte order,
 * canonicalization, digest-byte selection, midpoint conversion and Gaussian
 * transform reproduce `RngDomain` and `mode_gaussian` in
 * `python/gaussian_fixture.py`. They are part of the scientific realization
 * identity. Changing one requires a new protocol selector/domain and new
 * independent reference vectors, rather than silently changing `mode_hash_v1`.
 * The application-specific key and extraction format are defined below;
 * neither SHA-256 nor the cited parallel-RNG literature specifies that format.
 *
 * @par Reproducibility, statistics and validation
 * Fixed-width unsigned hashing and binary64 midpoint uniforms are exact across
 * the supported CPU/GPU backends. Kokkos log/sqrt/sin/cos and subsequent FFTs
 * may round differently; complete particle snapshots are not promised to be
 * byte-identical across backends. Gaussian moment statements below refer to
 * ideal independent continuous uniforms. This finite deterministic hash mapping
 * approximates that model; using disjoint digest bits does not prove their
 * statistical independence, and distinct keys are not promised distinct outputs.
 * TestCosmologyICRandom.cpp checks nine independent Python hashlib/struct/math
 * vectors: every digest word and uniform exactly, Gaussian components within
 * 8e-15 absolute error, conjugate pairs, high unsigned seeds and reordered calls.
 * Those checks establish protocol compatibility, not a general statistical RNG
 * certification. Production IC checks and saved-field comparisons exercise the
 * surrounding spectrum, FFT and particle initialization separately.
 *
 * @par Execution and cost
 * All functions are host/device callable and use automatic per-thread storage.
 * There are no MPI calls, atomics, shared mutable RNG state or host/device copies
 * inside this header. Each draw evaluates one 64-round SHA-256 compression and
 * a Box-Muller transform. The 64-byte block and 64-word schedule have fixed
 * size; a GPU compiler may place or spill them into thread-local memory, so
 * register occupancy and performance need measurement for the chosen backend.
 * Statelessness alone is not a throughput guarantee.
 *
 * @par External references and their scope
 * - NIST, <a href="https://doi.org/10.6028/NIST.FIPS.180-4">FIPS 180-4</a>
 *   @cite nist2015sha256 specifies the SHA-256 operations, constants, padding and
 *   compression used here. Section references are given beside the stages.
 * - Box and Muller (1958),
 *   <a href="https://doi.org/10.1214/aoms/1177706645">A Note on the Generation
 *   of Random Normal Deviates</a> @cite box1958normal supplies the normal
 *   transformation; modeGaussian() explains its complex normalization.
 * - Salmon et al. (2011),
 *   <a href="https://doi.org/10.1145/2063384.2063405">Parallel Random Numbers:
 *   As Easy as 1, 2, 3</a> @cite salmon2011parallel gives the stateless keyed
 *   parallel-generation context. This implementation uses SHA-256 to match the
 *   saved Python protocol; it does not implement Random123/Philox or inherit
 *   their published statistical and performance results.
 */
#ifndef IPPL_COSMOLOGY_IC_RANDOM_H
#define IPPL_COSMOLOGY_IC_RANDOM_H

#include <Kokkos_Core.hpp>
#include <Kokkos_Complex.hpp>
#include <Kokkos_MathematicalConstants.hpp>
#include <Kokkos_MathematicalFunctions.hpp>
#include <cstdint>

namespace cosmology {
namespace icRandomDetail {

/**
 * @brief SHA256 state words of the canonical mode key and its conjugation flag.
 *
 * words_m stores the numerical values of the eight SHA-256 output words H0..H7,
 * after the final feed-forward addition. Serializing each word most-significant
 * byte first gives the standard 32 digest bytes; the in-memory byte order of this
 * C++ struct is irrelevant. modeUniform() explicitly converts those serialized
 * bytes to the little-endian integers required by the application protocol.
 * conjugate_m is application metadata and is not part of the SHA-256 digest.
 * The fixed-vector regression checks all words independently of floating-point
 * transcendental roundoff. This type owns no allocation or shared state.
 */
struct ModeDigest {
    std::uint32_t words_m[8]; ///< SHA256 digest, serialized big-endian word by word.
    bool conjugate_m; ///< True if the requested mode is the negative canonical member.
};

/**
 * @brief Rotate a 32-bit SHA256 word right, preserving all 32 bits.
 * @details Implements @f$\mathrm{ROTR}^{n}(x)=(x\gg n)\lor(x\ll(32-n))@f$
 * from FIPS 180-4, Sec. 3.2 @cite nist2015sha256. Unsigned shifts make the
 * operation independent of signed right-shift conventions. Neither zero nor
 * 32 is accepted by the helper's contract, because a shift by 32 is invalid.
 * @param value Unsigned word to rotate.
 * @param count Fixed SHA256 rotation count, strictly between zero and 32.
 * @return Rotated unsigned word.
 */
KOKKOS_INLINE_FUNCTION std::uint32_t rotateRight(std::uint32_t value, unsigned count) {
    return (value >> count) | (value << (32U - count));
}

/**
 * @brief Hash the exact one-block signed-mode message with SHA256.
 *
 * @par Input message: exactly 50 bytes before SHA padding
 * The canonical member has its first nonzero Cartesian component positive.
 * This table describes serialized bytes, not C++ struct layout:
 *
 * Byte offsets | Length | Contents
 * ------------ | ------ | --------
 * 0..29 | 30 | 29 ASCII characters `IPPL-band-limited-Gaussian-v1`, then byte 0
 * 30..37 | 8 | Seed, unsigned uint64, least-significant byte first
 * 38..41 | 4 | Canonical x component, signed int32 encoded modulo 2^32, little-endian
 * 42..45 | 4 | Canonical y component, same encoding
 * 46..49 | 4 | Canonical z component, same encoding
 *
 * Casting a negative canonical component to uint32 specifies its modulo-2^32
 * encoding. Explicit shifts then serialize it without host endianness, alignment
 * or struct-padding assumptions. INT32_MIN is excluded because its negation
 * cannot be represented as int32; DC has no canonical nonzero member.
 *
 * @par SHA-256 stages and the two byte orders
 * The application message uses little-endian integers. SHA-256 then treats that
 * message as bytes and uses its own standard big-endian parsing and length
 * encoding. A 50-byte/400-bit message fits one padded 64-byte block: byte 50 is
 * 0x80, bytes 51..55 are zero and bytes 56..63 contain big-endian 400 (0x0190).
 * The static assertion prevents a future domain change from silently needing
 * a second block. This specialized helper is not an arbitrary-length hash API.
 *
 * FIPS 180-4 @cite nist2015sha256 defines padding/parsing in Secs. 5.1.1/5.2.1,
 * the initial state in Sec. 5.3.3, the round functions/constants in
 * Secs. 4.1.2/4.2.2 and schedule/compression/feed-forward in Sec. 6.2.2.
 * Code annotations below map those stages to the standard. Additions use
 * unsigned modulo-2^32 arithmetic; the return value includes the initial-state
 * feed-forward, rather than exposing the working variables alone.
 *
 * Execution and temporary arrays are local to the calling CPU/GPU thread.
 * The routine performs no dynamic allocation, synchronization or explicit
 * host/device transfer; compiler-generated local-memory traffic is possible.
 *
 * @param seed Full unsigned 64-bit realization seed.
 * @param kx Signed physical integer x mode, not a wrapped FFT storage index.
 * @param ky Signed physical integer y mode.
 * @param kz Signed physical integer z mode.
 * @return Canonical digest and whether the requested result must be conjugated.
 * @pre The mode is nonzero and no component equals INT32_MIN. Invalid calls
 * abort on host or device; callers exclude DC before requesting a random draw.
 */
KOKKOS_INLINE_FUNCTION ModeDigest modeDigest(std::uint64_t seed, std::int32_t kx,
                                             std::int32_t ky, std::int32_t kz) {
    constexpr std::int32_t MinimumComponent = -2147483647 - 1;
    if ((kx == 0 && ky == 0 && kz == 0) || kx == MinimumComponent
        || ky == MinimumComponent || kz == MinimumComponent) {
        Kokkos::abort("Cosmology mode RNG requires a nonzero, conjugatable int32 mode");
    }
    const std::int32_t first = kx != 0 ? kx : (ky != 0 ? ky : kz);
    const bool conjugate = first < 0;
    const std::int32_t components[3] = {
        conjugate ? -kx : kx, conjugate ? -ky : ky, conjugate ? -kz : kz};
    constexpr char Domain[] = "IPPL-band-limited-Gaussian-v1";
    constexpr unsigned DomainBytes = sizeof(Domain);
    constexpr unsigned MessageBytes = DomainBytes + 8U + 3U * 4U;
    static_assert(MessageBytes <= 55U, "Mode key must fit a single SHA256 block");
    unsigned char block[64] = {};
    for (unsigned index = 0; index < DomainBytes; ++index)
        block[index] = static_cast<unsigned char>(Domain[index]);
    for (unsigned byte = 0; byte < 8; ++byte)
        block[DomainBytes + byte] = static_cast<unsigned char>(seed >> (8U * byte));
    for (unsigned component = 0; component < 3; ++component) {
        // Signed-to-unsigned conversion specifies two's-complement bytes modulo 2^32.
        const auto encoded = static_cast<std::uint32_t>(components[component]);
        for (unsigned byte = 0; byte < 4; ++byte)
            block[DomainBytes + 8U + 4U * component + byte] =
                static_cast<unsigned char>(encoded >> (8U * byte));
    }
    // FIPS 180-4 Sec. 5.1.1: append one bit, zero-fill, then the 64-bit bit count.
    block[MessageBytes] = 0x80U;
    constexpr std::uint64_t MessageBits = MessageBytes * 8ULL;
    for (unsigned byte = 0; byte < 8; ++byte)
        block[63U - byte] = static_cast<unsigned char>(MessageBits >> (8U * byte));

    // Secs. 5.2.1 and 6.2.2: parse W[0..15] big-endian, then expand to W[0..63].
    std::uint32_t schedule[64];
    for (unsigned index = 0; index < 16; ++index) {
        schedule[index] = (std::uint32_t(block[4U * index]) << 24U)
                        | (std::uint32_t(block[4U * index + 1U]) << 16U)
                        | (std::uint32_t(block[4U * index + 2U]) << 8U)
                        | std::uint32_t(block[4U * index + 3U]);
    }
    for (unsigned index = 16; index < 64; ++index) {
        const auto left = schedule[index - 15U];
        const auto right = schedule[index - 2U];
        const auto sigma0 = rotateRight(left, 7U) ^ rotateRight(left, 18U) ^ (left >> 3U);
        const auto sigma1 = rotateRight(right, 17U) ^ rotateRight(right, 19U) ^ (right >> 10U);
        schedule[index] = schedule[index - 16U] + sigma0 + schedule[index - 7U] + sigma1;
    }
    // Sec. 4.2.2: K[0..63], fixed SHA-256 constants, not seed-dependent values.
    constexpr std::uint32_t RoundConstants[64] = {
        0x428a2f98U, 0x71374491U, 0xb5c0fbcfU, 0xe9b5dba5U,
        0x3956c25bU, 0x59f111f1U, 0x923f82a4U, 0xab1c5ed5U,
        0xd807aa98U, 0x12835b01U, 0x243185beU, 0x550c7dc3U,
        0x72be5d74U, 0x80deb1feU, 0x9bdc06a7U, 0xc19bf174U,
        0xe49b69c1U, 0xefbe4786U, 0x0fc19dc6U, 0x240ca1ccU,
        0x2de92c6fU, 0x4a7484aaU, 0x5cb0a9dcU, 0x76f988daU,
        0x983e5152U, 0xa831c66dU, 0xb00327c8U, 0xbf597fc7U,
        0xc6e00bf3U, 0xd5a79147U, 0x06ca6351U, 0x14292967U,
        0x27b70a85U, 0x2e1b2138U, 0x4d2c6dfcU, 0x53380d13U,
        0x650a7354U, 0x766a0abbU, 0x81c2c92eU, 0x92722c85U,
        0xa2bfe8a1U, 0xa81a664bU, 0xc24b8b70U, 0xc76c51a3U,
        0xd192e819U, 0xd6990624U, 0xf40e3585U, 0x106aa070U,
        0x19a4c116U, 0x1e376c08U, 0x2748774cU, 0x34b0bcb5U,
        0x391c0cb3U, 0x4ed8aa4aU, 0x5b9cca4fU, 0x682e6ff3U,
        0x748f82eeU, 0x78a5636fU, 0x84c87814U, 0x8cc70208U,
        0x90befffaU, 0xa4506cebU, 0xbef9a3f7U, 0xc67178f2U};
    // Sec. 5.3.3: the SHA-256 initial hash state H^(0), not an RNG stream state.
    constexpr std::uint32_t InitialState[8] = {
        0x6a09e667U, 0xbb67ae85U, 0x3c6ef372U, 0xa54ff53aU,
        0x510e527fU, 0x9b05688cU, 0x1f83d9abU, 0x5be0cd19U};
    auto a = InitialState[0], b = InitialState[1], c = InitialState[2], d = InitialState[3];
    auto e = InitialState[4], f = InitialState[5], g = InitialState[6], h = InitialState[7];
    // Sec. 6.2.2: 64 rounds. sigma0/sigma1 here are the standard capital-Sigma
    // functions; the earlier schedule uses the distinct lower-case-sigma functions.
    for (unsigned index = 0; index < 64; ++index) {
        const auto sigma1 = rotateRight(e, 6U) ^ rotateRight(e, 11U) ^ rotateRight(e, 25U);
        const auto choice = (e & f) ^ ((~e) & g);
        const auto firstTerm = h + sigma1 + choice + RoundConstants[index] + schedule[index];
        const auto sigma0 = rotateRight(a, 2U) ^ rotateRight(a, 13U) ^ rotateRight(a, 22U);
        const auto majority = (a & b) ^ (a & c) ^ (b & c);
        const auto secondTerm = sigma0 + majority;
        h = g; g = f; f = e; e = d + firstTerm;
        d = c; c = b; b = a; a = firstTerm + secondTerm;
    }
    // Sec. 6.2.2: feed forward H^(0) to obtain the one-block digest H^(1).
    return {{InitialState[0] + a, InitialState[1] + b, InitialState[2] + c,
             InitialState[3] + d, InitialState[4] + e, InitialState[5] + f,
             InitialState[6] + g, InitialState[7] + h}, conjugate};
}

/**
 * @brief Reverse a digest word's byte significance without host-endian assumptions.
 * @details This is the protocol conversion after SHA-256, not a change to its
 * compression. For example, word 0x12345678 denotes digest bytes 12 34 56 78;
 * reading those bytes little-endian gives 0x78563412. The explicit operations
 * produce the same result on a little- or big-endian machine.
 * @param word One standard big-endian digest word.
 * @return The integer obtained by interpreting its four serialized bytes little-endian.
 */
KOKKOS_INLINE_FUNCTION std::uint32_t reverseBytes(std::uint32_t word) {
    return (word >> 24U) | ((word >> 8U) & 0x0000ff00U)
         | ((word << 8U) & 0x00ff0000U) | (word << 24U);
}

/**
 * @brief Recover an exactly representable open-interval midpoint from digest bytes.
 *
 * For index j=0 or 1, interpret digest bytes [8j,8j+8) as little-endian uint64
 * @f$B_j@f$, keep its high 52 bits @f$b_j=\lfloor B_j/2^{12}\rfloor@f$, and set
 * @f[
 * u_j=\frac{b_j+1/2}{2^{52}},\qquad
 * 2^{-53}\le u_j\le 1-2^{-53}.
 * @f]
 * Only digest bytes 0..15 are used for the two draws; bytes 16..31 remain part
 * of the full digest checked by regression. The two disjoint input slices are
 * used as pseudorandom uniforms, without claiming a proof of independence.
 *
 * Why 52 bits rather than 53? Binary64 represents all 52-bit integers and their
 * half-integer midpoints exactly. Dividing by a power of two is also exact.
 * A 53-bit integer plus 1/2 can round upward at the top of the range, producing
 * the excluded endpoint 1. The midpoint rule avoids both endpoints and log(0)
 * without rejection sampling, clamping or an order-dependent extra draw.
 *
 * @param digest SHA256 output words from modeDigest; not raw host-memory bytes.
 * @param index Zero or one, selecting bytes [0,8) or [8,16), respectively.
 * @return Exactly representable (uint52 + 1/2)/2^52, strictly between zero and one.
 * @pre index is 0 or 1; this internal helper does not perform a range check.
 * @see modeGaussian
 */
KOKKOS_INLINE_FUNCTION double modeUniform(const ModeDigest& digest, unsigned index) {
    const auto low = std::uint64_t(reverseBytes(digest.words_m[2U * index]));
    const auto high = std::uint64_t(reverseBytes(digest.words_m[2U * index + 1U]));
    const auto bits = low | (high << 32U);
    constexpr double UniformDenominator = 4503599627370496.0; // Exact 2^52 protocol constant.
    return (static_cast<double>(bits >> 12U) + 0.5) / UniformDenominator;
}

} // namespace icRandomDetail

/**
 * @brief Draw one unit-variance complex Gaussian keyed by seed and physical integer mode.
 *
 * @par Complex Box-Muller normalization
 * In the ideal model, independent continuous U(0,1) variables give independent
 * unit normal deviates @f$Z_1=\sqrt{-2\ln u_1}\cos(2\pi u_2)@f$ and
 * @f$Z_2=\sqrt{-2\ln u_1}\sin(2\pi u_2)@f$ @cite box1958normal.
 * For a complex Fourier coefficient we need unit TOTAL variance, so set
 * @f[
 * G=\frac{Z_1+iZ_2}{\sqrt{2}}
 *   =\sqrt{-\ln u_1}\,[\cos(2\pi u_2)+i\sin(2\pi u_2)].
 * @f]
 * Hence, in that ideal model, @f$E[G]=0@f$,
 * @f$\mathrm{Var}(\Re G)=\mathrm{Var}(\Im G)=1/2@f$ and
 * @f$E[|G|^2]=1@f$. Using the real-normal radius sqrt(-2 log u1) directly here
 * would double the intended power. This is a Gaussian-amplitude prescription:
 * the amplitude fluctuates; it is not a fixed-amplitude/phase-only realization.
 *
 * @par Actual finite draw and conjugation
 * modeUniform() supplies deterministic 52-bit midpoint values. The normal
 * distribution and moments above describe the target model, not exact continuum
 * identities for this finite mapping. In particular, before transcendental
 * rounding @f$|G|\le\sqrt{53\ln 2}@f$, because @f$u_1\ge2^{-53}@f$.
 * The canonical member uses the expression above; requesting its opposite
 * negates only the imaginary result. Conjugation is exact for repeated calls
 * with identical arithmetic, including modes evaluated on different ranks.
 *
 * @par Fourier normalization and caller responsibilities
 * With the code's forward FFT normalization 1/N^3 and inverse unnormalized,
 * @f$\delta(\boldsymbol x)=\sum_{\boldsymbol m}\delta_{0,\boldsymbol m}
 * e^{i\boldsymbol k\cdot\boldsymbol x}@f$. The convention
 * @f$E[|\delta_{0,\boldsymbol m}|^2]=P_0(k)/V@f$, @f$V=L^3@f$, therefore gives
 * @f$\delta_{0,\boldsymbol m}=\sqrt{P_0(k)/V}\,G_{\boldsymbol m}@f$.
 * P has units of volume, so both G and delta are dimensionless. No extra N^3 or
 * sqrt(2) factor belongs in this function. For cell-centred lattice samples,
 * Simulation::initializeModes() additionally applies
 * @f$\exp[i\pi(m_x+m_y+m_z)/N]@f$. The same caller excludes DC/Nyquist modes
 * and applies the common cutoff; growth and 1LPT displacements occur later.
 *
 * Integer digest/uniform results match the Python protocol exactly. Kokkos
 * host/device log, sqrt and sin/cos may differ at roundoff, and the surrounding
 * FFT/reduction order may differ as well. This interface promises a stable
 * mode key, not bitwise particle agreement across backends. It uses per-thread
 * execution/memory with no shared RNG state or explicit host/device transfers.
 *
 * @param seed Full unsigned 64-bit realization seed.
 * @param kx Signed physical integer x mode.
 * @param ky Signed physical integer y mode.
 * @param kz Signed physical integer z mode.
 * @return Unit-variance Kokkos complex Gaussian coefficient before physical scaling.
 * @pre Nonzero mode with all components in [-2147483647,2147483647].
 * @see icRandomDetail::modeDigest icRandomDetail::modeUniform
 * @see Simulation::initializeModes cosmology_numerics
 */
KOKKOS_INLINE_FUNCTION Kokkos::complex<double> modeGaussian(
    std::uint64_t seed, std::int32_t kx, std::int32_t ky, std::int32_t kz) {
    const auto digest = icRandomDetail::modeDigest(seed, kx, ky, kz);
    const double u1 = icRandomDetail::modeUniform(digest, 0U);
    const double u2 = icRandomDetail::modeUniform(digest, 1U);
    const double radius = Kokkos::sqrt(-Kokkos::log(u1));
    const double angle = 2 * Kokkos::numbers::pi_v<double> * u2;
    const double real = radius * Kokkos::cos(angle);
    const double imaginary = radius * Kokkos::sin(angle);
    return {real, digest.conjugate_m ? -imaginary : imaginary};
}

} // namespace cosmology
#endif
