include:
  - remote: "https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml"

.pr-number-extractor:
  before_script:
    - echo "CI_PROJECT_URL=$CI_PROJECT_URL"
    - echo "CI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA"
    - |
      if [[ "$CI_COMMIT_REF_NAME" =~ pr([0-9]+)$ ]]; then
        export PR_NUMBER="PR-${BASH_REMATCH[1]}"
      else
        export PR_NUMBER="$CI_COMMIT_REF_NAME"
      fi
    - echo "PR_NUMBER=$PR_NUMBER"

stages:
  - ippl_build
  - ippl_test
