#!/usr/bin/env python3
"""
create_Nodes1DOracleData.py — write Nodes1DOracleData.h from SciPy reference values.

Families (interval [-1, 1] unless noted):
  GL           scipy.special.roots_legendre(n)
  GLL          endpoints ±1; interior = roots_jacobi(n-2, 1, 1);
               w_i = 2 / (n(n-1) [P_{n-1}(x_i)]^2)
  JAC_CHEB     scipy.special.roots_jacobi(n, -0.5, -0.5)
  JAC_11       scipy.special.roots_jacobi(n, 1.0, 1.0)
  GL_AFFINE_01 affine map of GL: x'=(x+1)/2, w'=w/2 on [0, 1] (AFFINE_NS)

To add nodal counts, edit NS (and AFFINE_NS if needed) and regenerate. The
header also emits GL_SAMPLES / GLL_SAMPLES / JAC_CHEB_SAMPLES / JAC_11_SAMPLES
/ GL_AFFINE_01_SAMPLES so the C++ unit tests pick up new n automatically.

Usage:
  python3 create_Nodes1DOracleData.py
  python3 create_Nodes1DOracleData.py -o Nodes1DOracleData.h
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
from scipy.special import eval_legendre, roots_jacobi, roots_legendre

NS = (2, 3, 7, 10, 17, 64)
AFFINE_NS = (7,)


def gll_nodes_weights(n: int) -> tuple[np.ndarray, np.ndarray]:
    nodes = np.zeros(n)
    weights = np.zeros(n)
    nodes[0], nodes[-1] = -1.0, 1.0
    bw = 2.0 / (n * (n - 1))
    weights[0] = weights[-1] = bw
    if n > 2:
        interior, _ = roots_jacobi(n - 2, 1.0, 1.0)
        nodes[1:-1] = interior
        p = eval_legendre(n - 1, interior)
        weights[1:-1] = 2.0 / (n * (n - 1) * (p**2))
    return nodes, weights


def fmt_array(vals: np.ndarray) -> str:
    parts = []
    for i, v in enumerate(vals):
        if i and i % 4 == 0:
            parts.append("\n  ")
        parts.append(f"{v: .17e}")
        if i + 1 < len(vals):
            parts.append(", ")
    return "".join(parts)


def dump_block(lines: list[str], tag: str, n: int, x: np.ndarray, w: np.ndarray) -> None:
    lines.append(f"// {tag} n={n}")
    lines.append(f"inline constexpr double {tag}_N{n}_NODES[{n}] = {{")
    lines.append(f"  {fmt_array(x)}")
    lines.append("};")
    lines.append(f"inline constexpr double {tag}_N{n}_WEIGHTS[{n}] = {{")
    lines.append(f"  {fmt_array(w)}")
    lines.append("};")
    lines.append("")


def dump_sample_table(lines: list[str], tag: str, ns: tuple[int, ...]) -> None:
    lines.append(f"inline constexpr OracleSample {tag}_SAMPLES[{len(ns)}] = {{")
    for n in ns:
        lines.append(f"    {{{n}, {tag}_N{n}_NODES, {tag}_N{n}_WEIGHTS}},")
    lines.append("};")
    lines.append("")


def build_header() -> str:
    lines: list[str] = [
        "// Auto-generated by create_Nodes1DOracleData.py (SciPy reference).",
        "// Do not edit by hand — regenerate with:",
        "//   python3 create_Nodes1DOracleData.py",
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace nodes1d_oracle {",
        "",
        "struct OracleSample {",
        "    std::size_t n;",
        "    const double* nodes;",
        "    const double* weights;",
        "};",
        "",
    ]

    for n in NS:
        x, w = roots_legendre(n)
        dump_block(lines, "GL", n, x, w)

        x, w = gll_nodes_weights(n)
        dump_block(lines, "GLL", n, x, w)

        x, w = roots_jacobi(n, -0.5, -0.5)
        dump_block(lines, "JAC_CHEB", n, x, w)

        x, w = roots_jacobi(n, 1.0, 1.0)
        dump_block(lines, "JAC_11", n, x, w)

    for n in AFFINE_NS:
        x, w = roots_legendre(n)
        dump_block(lines, "GL_AFFINE_01", n, 0.5 * (x + 1.0), 0.5 * w)

    lines.append("// Index tables — unit tests iterate these; add n in NS / AFFINE_NS above.")
    dump_sample_table(lines, "GL", NS)
    dump_sample_table(lines, "GLL", NS)
    dump_sample_table(lines, "JAC_CHEB", NS)
    dump_sample_table(lines, "JAC_11", NS)
    dump_sample_table(lines, "GL_AFFINE_01", AFFINE_NS)

    lines.append("}  // namespace nodes1d_oracle")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).with_name("Nodes1DOracleData.h"),
        help="Output header path (default: Nodes1DOracleData.h next to this script)",
    )
    args = ap.parse_args()
    text = build_header()
    args.output.write_text(text)
    print(f"Wrote {args.output} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
