//
// Class TruncatedGreenParticleInteraction
//   This class implements the short-range part of the Ewald Green function split by evaluating the
//   gradient of forceConstant * erfc(alpha * r) / r. Below regularization_cutoff, the singular
//   Coulomb contribution is replaced by a linear force that matches continuously at the cutoff.
//   The long-range part is handled by FFTTruncatedGreenPeriodicPoissonSolver.
//
//   It assumes that ParticleContainer implements a function forAllPairs() to iterate over all
//   relevant particle pairs.
//

#ifndef IPPL_TRUNCATEDGREEN_SHORTRANGE_H
#define IPPL_TRUNCATEDGREEN_SHORTRANGE_H

#include "ParticleInteractionBase.h"

namespace ippl {
    /*!
     * TruncatedGreenParticleInteraction class definition.
     * @tparam ParticleContainer particle container type
     * @tparam VectorAttribute type to store vector valued attributes
     * @tparam ScalarAttribute type to store scalar valued attributes
     * evaluates truncated short range interaction F = - q * forceConstant grad [(1 - erf(alpha *
     * r)) / r].
     */
    template <typename ParticleContainer, typename VectorAttribute, typename ScalarAttribute>
    class TruncatedGreenParticleInteraction : public ParticleInteractionBase<ParticleContainer> {
    public:
        using Base            = ParticleInteractionBase<ParticleContainer>;
        using Vector_t        = typename VectorAttribute::value_type;
        using Scalar_t        = typename ScalarAttribute::value_type;
        using execution_space = typename VectorAttribute::execution_space;
        static_assert(std::is_same_v<execution_space, typename ScalarAttribute::execution_space>);

    public:
        /*!
         * @param pc Particle container
         * @param F Field attribute, where the evaluated field will be added to
         * @param R Position attribute
         * @param QM Charge or Mass like attribute determining the force magnitued
         * @param params Parameters, containing at least 'alpha', 'force_constant' and 'rcut'. alpha
         * controls the Ewald split, force_constant scales the interaction, and rcut determines the
         * maximal contributing pair distance. The optional positive regularization_cutoff controls
         * the near-origin softening and defaults to 1e-9.
         */
        TruncatedGreenParticleInteraction(const ParticleContainer& pc, VectorAttribute& F,
                                          const VectorAttribute& R, const ScalarAttribute& QM,
                                          const ParameterList& params)
            : Base(pc, params)
            , Field_m(F)
            , R_m(R)
            , QM_m(QM) {
            if (!this->params_m.contains("regularization_cutoff")) {
                this->params_m.template add<Scalar_t>("regularization_cutoff",
                                                      static_cast<Scalar_t>(1.0e-9));
            }
        }

        ~TruncatedGreenParticleInteraction() override = default;

        /*!
         * Evaluates the short range interactions F = - q * forceConstant grad [(1 - erf(alpha *
         * r)) / r].
         */
        void solve() override;

    private:
        /*!
         * Helper function to compute the field = - q * forceConstant grad [(1 - erf(alpha *
         * r)) / r]. generated by an interacting particle
         */
        KOKKOS_INLINE_FUNCTION static constexpr Vector_t fieldFromPair(const Vector_t& dist,
                                                                       Scalar_t r2, Scalar_t alpha,
                                                                       Scalar_t forceConstant,
                                                                       Scalar_t qm, Scalar_t reg);

        ///! The electric or gravitational field
        VectorAttribute& Field_m;
        ///! Positions of the particles
        const VectorAttribute& R_m;
        ///! Charge or Mass of the particles
        const ScalarAttribute& QM_m;
    };
}  // namespace ippl

#include "TruncatedGreenParticleInteraction.hpp"

#endif  // IPPL_TRUNCATEDGREEN_SHORTRANGE_H
