#!/bin/bash
#
# OPAL Toolchain Build recipe for the Google Test framework
#
# https://github.com/google/googletest
#
P=googletest
V=${GTEST_VERSION:-1.11.0}

trap "otb_exit" EXIT

FNAME="$P-release-$V.tar.gz"
DOWNLOAD_URL="https://github.com/google/googletest/archive/release-$V/${FNAME}"
SRC_FILE="${OTB_DOWNLOAD_DIR}/${FNAME}"

# download
test -r "${SRC_FILE}" \
    || curl -L --output "$_" "${DOWNLOAD_URL}" || exit ${OTB_ERR_DOWNLOAD}

# unpack
mkdir -p "${OTB_SRC_DIR}/$P" && cd "$_" || exit ${OTB_ERR_SYSTEM}
tar xvf "${SRC_FILE}" || exit ${OTB_ERR_UNTAR}

# configure
mkdir -p "${OTB_SRC_DIR}/$P/build" && cd "$_" || exit ${OTB_ERR_SYSTEM}
cmake \
	-DCMAKE_INSTALL_PREFIX="${OTB_PREFIX}" \
        -DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_C_FLAGS_INIT="-fPIC" \
	-DCMAKE_CXX_FLAGS_INIT="-fPIC" \
	"${OTB_SRC_DIR}/$P/$P-release-$V" || exit ${OTB_ERR_CONFIGURE}

# compile and install
make -j ${NJOBS} || exit ${OTB_ERR_MAKE}
make install || exit ${OTB_ERR_INSTALL}

# Local Variables:
# mode: shell-script-mode
# sh-basic-offset: 8
# End:

