/** @file MaterialViewer.h
 * @brief C++ generator for the combined Python material viewer and mesh report.
 * @ingroup chdr_output
 * @details Edit this template, then rebuild and rerun mesh-1 to change future
 * generated viewers. Editing a data-directory copy affects only that snapshot.
 * The emitted Python is documented in the student guide's output section.
 */
#ifndef IPPL_CHDR_MATERIAL_VIEWER_H
#define IPPL_CHDR_MATERIAL_VIEWER_H

#include <filesystem>
#include <fstream>
#include <stdexcept>

#include "MeshVisualization.h"

namespace chdr {

    /**
     * @brief Emit a self-contained interactive material viewer and mesh PDF report.
     * @ingroup chdr_output
     *
     * All geometry is embedded in millimetres; the generated script can be copied
     * or launched from any directory without YAML, JSON, CSV or the C++ executable.
     * PyVista renders the analytic dielectric boundary and a transparent outer
     * boundary of the vacuum region (domain minus radiator). It does not construct
     * every material voxel. The bounded diagnostic slices and metadata are embedded
     * from mesh.json and slices.csv after those files have been written. Running the
     * script first saves their four-panel Matplotlib report as a PDF, then opens
     * the interactive view. --pdf-only requires no PyVista or graphics display.
     * Data size scales with the preview sample count and MPI rank count, not the
     * full three-dimensional field. No additional collective or device copy occurs.
     *
     * @param outputDirectory Existing simulation output directory.
     * @pre mesh.json and slices.csv have been closed successfully by the root rank.
     * @post mesh-1_Materials.py contains all data and needs no companion files.
     * @note This host-only emitter does not launch Python, create a PDF, or open a
     * window. Those actions occur when the user runs the generated script.
     * @see writeMeshReportFunctions
     * @throws std::ios_base::failure If the generated script cannot be written.
     * @throws std::runtime_error If the diagnostic inputs cannot be opened.
     */
    inline void writeMaterialViewer(const std::filesystem::path& outputDirectory) {
        std::ifstream metadata(outputDirectory / "mesh.json");
        std::ifstream samples(outputDirectory / "slices.csv");
        if (!metadata || !samples) {
            throw std::runtime_error("Cannot read mesh diagnostics for the material viewer");
        }
        std::ofstream script(outputDirectory / "mesh-1_Materials.py");
        script.exceptions(std::ios::failbit | std::ios::badbit);
        script << R"CHDRPY(#!/usr/bin/env python3
"""ChDR material geometry and automatic mesh PDF report, generated by mesh-1.

Run: python mesh-1_Materials.py  (or add --show, as in OPALX).
Each run first writes mesh-1_Materials.pdf beside this script: the mesh
overview and three staircase slices formerly shown by visualize_mesh.py.
Drag to rotate, scroll to zoom, shift-drag to pan; checkboxes hide materials.
Use --pdf-only for just the PDF, --pdf PATH to change its destination,
or --save materials.png for the PDF plus a noninteractive 3D screenshot.

The interactive surfaces show analytic geometry. Vacuum occupies the domain
outside the radiator; its transparent outer boundary is displayed. PDF slices
contain actual IPPL epsilon samples; decimation can miss thin features.
All data are embedded: no sibling files or IPPL installation are required.
"""

import argparse
import csv
import io
import json
from pathlib import Path

MESH_METADATA = json.loads(r'''
)CHDRPY";
        script << metadata.rdbuf();
        script << R"CHDRPY(''')

SLICE_CSV = r''')CHDRPY";
        script << samples.rdbuf();
        script << R"CHDRPY('''

GEOMETRY = {
    "lower": MESH_METADATA["domain"]["lower"],
    "size": MESH_METADATA["domain"]["size"],
    "radiator": MESH_METADATA["radiator"],
    "epsilon_vacuum": MESH_METADATA["background_epsilon_r"],
    "epsilon_dielectric": MESH_METADATA["radiator"]["epsilon_r"],
}
)CHDRPY";
        writeMeshReportFunctions(script);
        script << R"CHDRPY(

def materialSurfaces():
    """Return the vacuum outer boundary and the closed dielectric surface."""
    import numpy as np
    import pyvista as pv

    lower = np.asarray(GEOMETRY["lower"], dtype=float)
    upper = lower + np.asarray(GEOMETRY["size"], dtype=float)
    bounds = tuple(value for pair in zip(lower, upper) for value in pair)
    outer = pv.Box(bounds=bounds).triangulate()
    radiator = GEOMETRY["radiator"]
    if radiator["type"] == "brick":
        brickLower = np.asarray(radiator["lower"], dtype=float)
        brickUpper = brickLower + np.asarray(radiator["size"], dtype=float)
        brickBounds = tuple(value for pair in zip(brickLower, brickUpper) for value in pair)
        return outer, pv.Box(bounds=brickBounds).triangulate()
    if radiator["type"] != "prism":
        raise ValueError(f"Unsupported radiator type: {radiator['type']}")
    bottom = np.asarray(radiator["vertices"], dtype=float)
    axis = np.asarray(radiator["axis"], dtype=float)
    # VTK's wedge base has an outward normal opposite the extrusion axis.
    # Canonicalize either input winding, also for non-Cartesian directions.
    if np.dot(np.cross(bottom[1] - bottom[0], bottom[2] - bottom[0]), axis) > 0:
        bottom = bottom[[0, 2, 1]]
    vertices = np.vstack((bottom, bottom + radiator["height"] * axis))
    wedge = pv.UnstructuredGrid({pv.CellType.WEDGE: np.arange(6).reshape(1, 6)}, vertices)
    dielectric = wedge.extract_surface(algorithm="dataset_surface").triangulate()
    return outer, dielectric


def buildScene(offScreen=False):
    """Create the interactive scene; return it and its material visibility controls."""
    import pyvista as pv

    outer, dielectric = materialSurfaces()
    plotter = pv.Plotter(off_screen=offScreen, window_size=(1100, 820),
                         title="ChDR: vacuum and dielectric")
    plotter.set_background("white")
    vacuumActors = [
        plotter.add_mesh(outer, color="#9ecae1", opacity=0.10, lighting=False),
        plotter.add_mesh(outer.extract_feature_edges(), color="#5d7b90", line_width=1.5),
    ]
    dielectricActor = plotter.add_mesh(dielectric, color="#d98b32", opacity=1.0,
                                       smooth_shading=False, show_edges=False)
    dielectricEdges = plotter.add_mesh(dielectric.extract_feature_edges(),
                                       color="#835116", line_width=2)
    groups = {"vacuum": vacuumActors, "dielectric": [dielectricActor, dielectricEdges]}

    def setVisible(material, visible):
        for actor in groups[material]:
            actor.SetVisibility(bool(visible))
        plotter.render()

    labels = [
        ("vacuum", f"Vacuum: epsilon_r = {GEOMETRY['epsilon_vacuum']:g}", "#5d7b90"),
        ("dielectric", f"Dielectric: epsilon_r = {GEOMETRY['epsilon_dielectric']:g}", "#d98b32"),
    ]
    for index, (material, label, color) in enumerate(labels):
        y = 55 - index * 35
        plotter.add_checkbox_button_widget(
            lambda checked, name=material: setVisible(name, checked),
            value=True, position=(15, y), size=23, color_on=color,
            color_off="#eeeeee", background_color="white")
        plotter.add_text(label, position=(48, y + 2), font_size=11, color="#243746")
    plotter.add_text("ChDR material geometry", position="upper_left", font_size=17,
                     color="#243746")
    plotter.add_text("Rotate: drag   Zoom: scroll   Pan: shift + drag",
                     position="upper_right", font_size=10, color="#52616b")
    plotter.add_axes(viewport=(0.82, 0.0, 1.0, 0.18))
    plotter.show_grid(xtitle="x [mm]", ytitle="y [mm]", ztitle="z [mm]",
                      color="#52616b", font_size=11)
    plotter.enable_trackball_style()
    plotter.view_isometric()
    plotter.camera.zoom(0.90)
    return plotter, groups, setVisible


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--show", action="store_true", help="write PDF and open interactive window (default)")
    mode.add_argument("--save", type=Path, help="write PDF and save a 3D PNG screenshot without a window")
    mode.add_argument("--pdf-only", action="store_true", help="write PDF only; no PyVista or display needed")
    parser.add_argument("--pdf", type=Path, default=Path(__file__).resolve().with_suffix(".pdf"),
                        help="PDF destination (default: mesh-1_Materials.pdf beside this script)")
    parser.add_argument("--dpi", type=int, default=180, help="resolution of rasterized PDF slice panels")
    parser.add_argument("--max-rank-boxes", type=int, default=64,
                        help="maximum MPI rank outlines in the PDF (0 hides them)")
    args = parser.parse_args()
    if args.pdf.suffix.lower() != ".pdf":
        parser.error("--pdf must name a .pdf file")
    if args.dpi <= 0 or args.max_rank_boxes < 0:
        parser.error("--dpi must be positive and --max-rank-boxes nonnegative")
    try:
        slices = list(csv.DictReader(io.StringIO(SLICE_CSV)))
        saveMeshReport(MESH_METADATA, slices, args.pdf, args.dpi, args.max_rank_boxes)
    except ImportError as error:
        raise SystemExit("The PDF report needs NumPy and Matplotlib: " + str(error)) from error
    except OSError as error:
        raise SystemExit("Cannot write mesh PDF report: " + str(error)) from error
    print(f"Saved {args.pdf.resolve()}", flush=True)
    if args.pdf_only:
        return
    try:
        plotter, _, _ = buildScene(offScreen=args.save is not None)
    except ImportError as error:
        raise SystemExit("This viewer needs NumPy and PyVista. Use the Python environment "
                         "that runs your OPALX viewer (for example ~/.venv-h6/bin/python). "
                         + str(error)) from error
    if args.save is not None:
        args.save.parent.mkdir(parents=True, exist_ok=True)
        plotter.show(screenshot=str(args.save), interactive=False)
        print(f"Saved {args.save.resolve()}")
    else:
        plotter.show()


if __name__ == "__main__":
    main()
)CHDRPY";
        script.close();
    }

}  // namespace chdr

#endif
