# -----------------------------------------------------------------------------
# AddIpplBenchmark.cmake
#
# Defines a helper function `add_ippl_benchmark()` to create a Google Benchmark executable linked
# against IPPL. It also generates a compile-time whitelist of IpplTimings timer names that the
# benchmark is allowed to emit to bencher.dev.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# ~~~
# add_ippl_benchmark(<name>
#   [SOURCES <src1> <src2> ...]        # default: <name>.cpp
#   [REPORT_TIMERS <t1> <t2> ...]      # whitelist of IpplTimings names
#   [IGNORE_TIMERS <t1> <t2> ...]      # blacklist of IpplTimings names
#   [NUM_PROCS <N>]                    # default: 1
#   [ARGS <arg1> <arg2> ...]           # args passed to the benchmark binary
#   [LABELS <lbl1> <lbl2> ...]         # extra ctest labels
# )
# ~~~
# -----------------------------------------------------------------------------
function(add_ippl_benchmark BENCH_NAME)
  set(options)
  set(oneValueArgs NUM_PROCS)
  set(multiValueArgs SOURCES REPORT_TIMERS IGNORE_TIMERS ARGS LABELS)
  cmake_parse_arguments(BENCH "${options}" "${oneValueArgs}" "${multiValueArgs}" ${ARGN})

  if(BENCH_REPORT_TIMERS AND BENCH_IGNORE_TIMERS)
    message(
      FATAL_ERROR
        "add_ippl_benchmark(${BENCH_NAME}): REPORT_TIMERS and IGNORE_TIMERS are mutually exclusive")
  endif()

  if(BENCH_SOURCES)
    set(_sources ${BENCH_SOURCES})
  else()
    set(_sources ${BENCH_NAME}.cpp)
  endif()

  add_executable(${BENCH_NAME} ${_sources})

  target_link_libraries(${BENCH_NAME} PRIVATE IPPL::ippl benchmark::benchmark)

  if(TARGET ippl_build_flags)
    target_link_libraries(${BENCH_NAME} PRIVATE ippl_build_flags)
  endif()

  target_include_directories(${BENCH_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}
                                                   ${CMAKE_CURRENT_BINARY_DIR})

  # Generate the timer whitelist header in the build tree.
  set(_timer_header "${CMAKE_CURRENT_BINARY_DIR}/${BENCH_NAME}_timers.h")

  if(BENCH_IGNORE_TIMERS)
    # For a blacklist we still emit all known names in the header and let the BMF writer drop
    # ignored ones at runtime. Until then, emit an empty list so the helper does not need to
    # enumerate every possible IpplTimings name.
    set(_timer_names)
  else()
    set(_timer_names ${BENCH_REPORT_TIMERS})
  endif()

  list(LENGTH _timer_names _num_timers)

  set(_entries)
  foreach(_name IN LISTS _timer_names)
    string(APPEND _entries "    \"${_name}\",\n")
  endforeach()

  string(
    CONCAT _header_content
           "#pragma once\n"
           "#include <array>\n"
           "#include <string_view>\n\n"
           "// Auto-generated by add_ippl_benchmark for ${BENCH_NAME}.\n"
           "// Empty list means all IpplTimings phases are reportable.\n"
           "inline constexpr std::array<std::string_view, ${_num_timers}> reportedTimers{\n"
           "${_entries}};\n")

  file(GENERATE OUTPUT ${_timer_header} CONTENT "${_header_content}")
endfunction()
